### PR TITLE
install dependencies, initialize app && setup dotenv, set up middleware, app listen on port 3000, added routes, &  error handlers

### PR DESCRIPTION
**Pull request by RobertMotion**

### CODE REVIEW

**Comment by che-perez** [comment]
Good Job Robert!!!!

**Comment by dlevenson44** [comment]
Looks good!

**Review by illlyo — APPROVED** [review]
message approved by illy

**Review by dlevenson44 — APPROVED** [review]
Looks gravy

**Review by che-perez — APPROVED** [review]

**Pull request merged**
